#Created by Solomon Laleye on 06/07/2025.
workflows:
  ios-workflow:
    name: iOS Build and TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SolomonAPIKey
    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "com.solomon.RandomPhotoGenerator"
        XCODE_PROJECT: "RandomPhotoGenerator.xcodeproj"
        XCODE_SCHEME: "RandomPhotoGenerator"
        APP_STORE_APPLE_ID: "6748310367"
      xcode: latest
      cocoapods: default
    scripts:
#      - name: Install CocoaPods dependencies
#        script: |
#          pod install --repo-update
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "New build number: $NEW_BUILD_NUMBER"
          agvtool new-version -all "$NEW_BUILD_NUMBER"
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - solomon@codemagic.io
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false
